---
- name: "Ensure TCP SYN Cookies is enabled"
  lineinfile:
      path: /etc/sysctl.d/99-sysctl.conf
      line: 'net.ipv4.tcp_syncookies=1'
      state: absent
  check_mode: yes
  register: presence
  no_log: true

  when:
      - rhel8_rule_1
  tags:
      - rsyslog
 
- name: set rule
  set_fact:
          rule_1_Ensure: "{{ 'true' if presence.found else 'false' if not presence.found else 'unknown' }}"
       

- name: "all result combined"
  set_fact:
     all_results: "{{ all_results|default({})|combine({'rule_1_Ensure':{'result': rule_1_Ensure|default(False), 'audits': rule_1_Ensure|default([])}}) }}"


