---
- block:
  - name: "007 - Setup GREP_PASS_MAX_DAYS"
    shell: grep "^PASS_MAX_DAYS" /etc/login.defs | awk '{ print $NF }'
    register: GREP_PASS_MAX_DAYS
    changed_when: no
    check_mode: no

  - name: "007 - Setup result"
    set_fact: 
      result_007: yes
      #    when: ('90' in GREP_PASS_MAX_DAYS.stdout) or
      #              (chage_max.rc == 0)

    when: ('99999' in GREP_PASS_MAX_DAYS.stdout)

  - name: "007 - Setup audit variable"
    set_fact:
       task_007: "{{ task_007|default([]) + [item] }}"
    with_items:
          - "{{ GREP_PASS_MAX_DAYS }}"
          #  - "{{ chage_max }}"

  - name: "007 - Set Password Expiration Days (Scored)"
    set_fact: 
      all_results: "{{ all_results|default({})|combine({'007':{'result':result_007|default(False), 'audits': task_007|default([])}}) }}"

  when: rule_007
  tags: rule_007
  ignore_errors: yes
